spring:
  application:
    name: myblog

  datasource:
    url: jdbc:mysql://myblog-db.cbimk02gozbw.ap-northeast-2.rds.amazonaws.com:3306/myblog
    username: admin
    password: dlsdudrh1!
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jmx:
    enabled: false

jwt:
  secret: gasfegqwdasdgasfegqwdasdgasfegqwdasdgasfegqwdasdgasfegqwdasqwdasdgasfegqwdasdgasfegqwdasqwdasdgasfegqwdasdgasfegqwdasd
  expiration: 3600000
  refresh:
    expiration: 86400000

logging:
  level:
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS, Asia/Seoul} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS, Asia/Seoul} %5p ${PID:- } --- [%t] %-40.40logger{39} : %m%n%wEx"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html